# Generated by Django 5.2.17 on 2026-08-06 16:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('code', models.CharField(help_text="Code court unique de l'établissement (ex: LYC-TANA)", max_length=20, unique=True, verbose_name='code')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Ex: +261340000000 ou 0340000000', regex='^\\+?[0-9]{10,15}$')], verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_ecoles/', verbose_name='logo')),
                ('devise', models.CharField(default='Ar', max_length=10, verbose_name='devise')),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, default=uuid.uuid4, help_text='Généré automatiquement si non fourni', max_length=150, null=True, unique=True, verbose_name="nom d'utilisateur")),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('ENSEIGNANT', 'Enseignant'), ('ETUDIANT', 'Étudiant'), ('RESPONSABLE', 'responsable Pédagogique'), ('SECRETARIAT', 'Secrétariat'), ('PARENT', 'Parent / Tuteur')], default='ETUDIANT', max_length=15, verbose_name='rôle')),
                ('genre', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], max_length=1, null=True, verbose_name='genre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('is_active', models.BooleanField(default=False, help_text="Détermine si l'utilisateur peut se connecter. Les étudiants ne peuvent pas se connecter.", verbose_name='compte actif')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Ex: +261340000000 ou 0340000000', regex='^\\+?[0-9]{10,15}$')], verbose_name='téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profils/', verbose_name='photo de profil')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='lieu de naissance')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='adresse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('groups', models.ManyToManyField(blank=True, help_text="Les groupes auxquels appartient l'utilisateur.", related_name='application_user_set', related_query_name='application_user', to='auth.group', verbose_name='groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='application_user_set', related_query_name='application_user', to='auth.permission', verbose_name='permissions utilisateur')),
                ('ecole', models.ForeignKey(blank=True, help_text='Établissement de rattachement (vide pour un super-administrateur plateforme).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='application.ecole', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: 2025-2026', max_length=20, verbose_name='libellé')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée'), ('ARCHIVEE', 'Archivée')], default='EN_PREPARATION', max_length=20, verbose_name='statut')),
                ('est_active', models.BooleanField(default=False, help_text='Une seule année active par établissement.', verbose_name='est active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='application.ecole', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Format: ANNEE-CODE-XXXX (ex: 2023-INF-0001)', max_length=20, verbose_name='matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='lieu de naissance')),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], max_length=1, verbose_name='genre')),
                ('nationalite', models.CharField(default='Malagasy', max_length=100, verbose_name='nationalité')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Ex: +261340000000 ou 0340000000', regex='^\\+?[0-9]{10,15}$')], verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='adresse email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_etudiants/', verbose_name='photo')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('ADMIS', 'Admis'), ('ABANDON', 'Abandon'), ('EXCLU', 'Exclu'), ('DIPLOME', 'Diplômé')], default='INSCRIT', max_length=10, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='application.ecole', verbose_name='établissement')),
                ('utilisateur', models.OneToOneField(blank=True, help_text="Compte utilisateur permettant à l'étudiant de se connecter (facultatif).", limit_choices_to={'role': 'ETUDIANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='compte de connexion')),
            ],
            options={
                'verbose_name': 'étudiant',
                'verbose_name_plural': 'étudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court de la filière (ex: INFO, GESTION)', max_length=10, verbose_name='code')),
                ('intitule', models.CharField(max_length=100, verbose_name='intitulé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duree_etudes', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='durée des études (années)')),
                ('capacite_max', models.PositiveSmallIntegerField(default=50, verbose_name='capacité maximale')),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='application.ecole', verbose_name='établissement')),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'role': 'RESPONSABLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='responsable pédagogique')),
            ],
            options={
                'verbose_name': 'filière',
                'verbose_name_plural': 'filières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 2nde C, Terminale S1', max_length=50, verbose_name='nom')),
                ('capacite_max', models.PositiveSmallIntegerField(default=40, verbose_name='capacité maximale')),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='application.anneescolaire', verbose_name='année scolaire')),
                ('titulaire', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_titulaire', to=settings.AUTH_USER_MODEL, verbose_name='professeur titulaire')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='application.filiere', verbose_name='filière')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['annee_scolaire', 'niveau__ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('REDOUBLANT', 'Redoublant'), ('TRANSFERE', 'Transféré'), ('ABANDON', 'Abandon'), ('EXCLU', 'Exclu'), ('DIPLOME', 'Diplômé')], default='ACTIVE', max_length=15, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='application.anneescolaire', verbose_name='année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='application.classe', verbose_name='classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='application.etudiant', verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-annee_scolaire__date_debut', 'classe'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: 6EME, 2ND, TLE, L1, etc.', max_length=10, verbose_name='code')),
                ('intitule', models.CharField(max_length=100, verbose_name='intitulé')),
                ('ordre', models.PositiveSmallIntegerField(help_text="Ordre d'affichage (1 pour le premier niveau)", verbose_name='ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='application.ecole', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'niveau',
                'verbose_name_plural': 'niveaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court de la matière (ex: MATH, PHYS)', max_length=10, verbose_name='code')),
                ('intitule', models.CharField(max_length=100, verbose_name='intitulé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='coefficient')),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('enseignant', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
                ('filiere', models.ForeignKey(blank=True, help_text='Laisser vide pour un niveau sans filière (ex: collège).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='application.filiere', verbose_name='filière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='application.niveau', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='application.niveau', verbose_name='niveau'),
        ),
        migrations.CreateModel(
            name='PaiementEcolage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='date de paiement')),
                ('date_echeance', models.DateField(verbose_name="date d'échéance")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('mois_couvert', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mois couvert')),
                ('mode_paiement', models.CharField(default='Espèces', help_text='Ex: Espèces, Virement, Chèque, etc.', max_length=50, verbose_name='mode de paiement')),
                ('reference', models.CharField(blank=True, help_text='Numéro de référence du paiement', max_length=50, null=True, verbose_name='référence')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_ecolage', to='application.anneescolaire', verbose_name='année scolaire')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_ecolage', to='application.etudiant', verbose_name='étudiant')),
                ('secretaire', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'SECRETARIAT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='secrétaire')),
            ],
            options={
                'verbose_name': "paiement d'écolage",
                'verbose_name_plural': "paiements d'écolage",
                'ordering': ['-date_paiement', 'etudiant'],
            },
        ),
        migrations.CreateModel(
            name='PresenceCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cours', models.DateField(verbose_name='date du cours')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('R', 'En retard'), ('E', 'Absence justifiée')], default='P', max_length=1, verbose_name='statut')),
                ('justificatif', models.TextField(blank=True, null=True, verbose_name='justificatif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='application.etudiant', verbose_name='étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='application.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'présence au cours',
                'verbose_name_plural': 'présences aux cours',
                'ordering': ['-date_cours', 'heure_debut', 'etudiant'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Salle 12, Labo Physique', max_length=50, verbose_name='nom')),
                ('capacite', models.PositiveSmallIntegerField(default=40, verbose_name='capacité')),
                ('type_salle', models.CharField(blank=True, help_text='Ex: Salle de classe, Laboratoire, Amphithéâtre', max_length=50, null=True, verbose_name='type')),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='application.ecole', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=3, verbose_name='jour')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='application.classe', verbose_name='classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_donnes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='application.matiere', verbose_name='matière')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='application.salle', verbose_name='salle')),
            ],
            options={
                'verbose_name': 'emploi du temps',
                'verbose_name_plural': 'emplois du temps',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='application.salle', verbose_name='salle'),
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='numéro')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('est_actif', models.BooleanField(default=False, verbose_name='est actif')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='application.anneescolaire', verbose_name='année scolaire')),
            ],
            options={
                'verbose_name': 'trimestre',
                'verbose_name_plural': 'trimestres',
                'ordering': ['annee_scolaire', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note')),
                ('date_evaluation', models.DateField(default=django.utils.timezone.now, verbose_name="date d'évaluation")),
                ('type_evaluation', models.CharField(help_text='Ex: Contrôle continu, Examen final, etc.', max_length=50, verbose_name="type d'évaluation")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application.etudiant', verbose_name='étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application.matiere', verbose_name='matière')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='saisie par')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application.trimestre', verbose_name='trimestre')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-date_evaluation', 'etudiant'],
            },
        ),
        migrations.CreateModel(
            name='TuteurEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('AUTRE', 'Autre')], max_length=10, verbose_name='relation')),
                ('est_contact_principal', models.BooleanField(default=False, verbose_name='contact principal')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteurs', to='application.etudiant', verbose_name='étudiant')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to=settings.AUTH_USER_MODEL, verbose_name='parent')),
            ],
            options={
                'verbose_name': 'tuteur',
                'verbose_name_plural': 'tuteurs',
            },
        ),
        migrations.AddConstraint(
            model_name='anneescolaire',
            constraint=models.UniqueConstraint(condition=models.Q(('est_active', True)), fields=('ecole',), name='unique_annee_active_par_ecole'),
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('ecole', 'libelle')},
        ),
        migrations.AlterUniqueTogether(
            name='etudiant',
            unique_together={('ecole', 'matricule'), ('ecole', 'nom', 'prenom', 'date_naissance')},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('ecole', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('ecole', 'code'), ('ecole', 'ordre')},
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(condition=models.Q(('filiere__isnull', True)), fields=('code', 'niveau'), name='unique_matiere_code_niveau_sans_filiere'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('code', 'filiere', 'niveau')},
        ),
        migrations.AlterUniqueTogether(
            name='presencecours',
            unique_together={('etudiant', 'matiere', 'date_cours')},
        ),
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together={('ecole', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together={('classe', 'jour', 'heure_debut', 'heure_fin')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('annee_scolaire', 'nom')},
        ),
        migrations.AddConstraint(
            model_name='trimestre',
            constraint=models.UniqueConstraint(condition=models.Q(('est_actif', True)), fields=('annee_scolaire',), name='unique_trimestre_actif_par_annee'),
        ),
        migrations.AlterUniqueTogether(
            name='trimestre',
            unique_together={('annee_scolaire', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'type_evaluation', 'trimestre')},
        ),
        migrations.AlterUniqueTogether(
            name='tuteuretudiant',
            unique_together={('parent', 'etudiant')},
        ),
    ]
