# Generated by Django 5.2.17 on 2026-08-06 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="date d'inscription"),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_evaluation',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="date d'évaluation"),
        ),
        migrations.AlterField(
            model_name='paiementecolage',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='date de paiement'),
        ),
    ]
