# Generated by Django 5.2.17 on 2026-08-07 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_inscription_date_inscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="frais d'inscription")),
                ('montant_annuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='écolage annuel')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolarite', to='application.anneescolaire', verbose_name='année scolaire')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolarite', to='application.filiere', verbose_name='filière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolarite', to='application.niveau', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'frais de scolarité',
                'verbose_name_plural': 'frais de scolarité',
                'ordering': ['annee_scolaire', 'niveau'],
                'unique_together': {('annee_scolaire', 'niveau', 'filiere')},
            },
        ),
    ]
