# Generated by Django 5.2.17 on 2026-08-07 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_fraisscolarite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='moyenne générale')),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rang')),
                ('effectif_classe', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='effectif de la classe')),
                ('mention', models.CharField(choices=[('FELICITATIONS', 'Félicitations'), ('ENCOURAGEMENTS', 'Encouragements'), ('TABLEAU_HONNEUR', "Tableau d'honneur"), ('AUCUNE', 'Aucune')], default='AUCUNE', max_length=20, verbose_name='mention')),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('REDOUBLE', 'Redouble'), ('NON_APPLICABLE', 'Non applicable (bulletin trimestriel)')], default='NON_APPLICABLE', max_length=20, verbose_name='décision')),
                ('est_valide', models.BooleanField(default=False, verbose_name='validé')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='date de génération')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='application.anneescolaire', verbose_name='année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='application.classe', verbose_name='classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='application.etudiant', verbose_name='étudiant')),
                ('trimestre', models.ForeignKey(blank=True, help_text='Vide pour un bulletin annuel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='application.trimestre', verbose_name='trimestre')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'bulletin',
                'verbose_name_plural': 'bulletins',
                'ordering': ['-annee_scolaire__date_debut', 'trimestre', 'etudiant'],
                'unique_together': {('etudiant', 'annee_scolaire', 'trimestre')},
            },
        ),
    ]
