# Generated by Django 5.2.17 on 2026-08-07 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('ATTESTATION', 'Attestation de fréquentation'), ('CERTIFICAT_REUSSITE', 'Certificat de réussite')], max_length=25, verbose_name='type de document')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=10, verbose_name='statut')),
                ('motif_refus', models.TextField(blank=True, null=True, verbose_name='motif de refus')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_documents', to='application.anneescolaire', verbose_name='année scolaire')),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_demandes', to=settings.AUTH_USER_MODEL, verbose_name='demandé par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_documents', to='application.etudiant', verbose_name='étudiant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_traites', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': 'demande de document',
                'verbose_name_plural': 'demandes de documents',
                'ordering': ['-date_demande'],
            },
        ),
    ]
