# Generated by Django 5.2.17 on 2026-08-07 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_demandedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portee', models.CharField(choices=[('ETABLISSEMENT', "Tout l'établissement"), ('CLASSE', 'Une classe'), ('ENSEIGNANTS', 'Les enseignants'), ('PARENTS', 'Les parents')], default='ETABLISSEMENT', max_length=20, verbose_name='portée')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_publiees', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('classe', models.ForeignKey(blank=True, help_text="Requis uniquement si portée = 'Une classe'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='application.classe', verbose_name='classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='application.ecole', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200, verbose_name='objet')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('est_lu', models.BooleanField(default=False, verbose_name='lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('NOTE', 'Nouvelle note'), ('ABSENCE', 'Absence'), ('PAIEMENT', 'Paiement enregistré'), ('BULLETIN', 'Bulletin disponible'), ('DOCUMENT', 'Document disponible'), ('ANNONCE', 'Nouvelle annonce'), ('MESSAGE', 'Nouveau message')], max_length=15, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('est_lue', models.BooleanField(default=False, verbose_name='lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
