# Generated by Django 5.2.17 on 2026-08-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_annonce_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='delegue',
            field=models.ForeignKey(blank=True, help_text='Étudiant représentant la classe (destinataire privilégié des documents des enseignants).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_delegue', to='application.etudiant', verbose_name='délégué de classe'),
        ),
    ]
