# Generated by Django 5.2.17 on 2026-08-07 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_classe_delegue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression')], max_length=15, verbose_name='action')),
                ('modele', models.CharField(help_text='Ex: Note, PaiementEcolage', max_length=50, verbose_name='modèle')),
                ('objet_id', models.PositiveIntegerField(verbose_name='identifiant objet')),
                ('objet_repr', models.CharField(max_length=255, verbose_name='représentation')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="date de l'action")),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_audit', to='application.ecole', verbose_name='établissement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journalisees', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
                'ordering': ['-date_action'],
            },
        ),
    ]
