# Generated by Django 5.2.17 on 2026-08-07 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOTE', 'Nouvelle note'), ('ABSENCE', 'Absence'), ('PAIEMENT', 'Paiement enregistré'), ('BULLETIN', 'Bulletin disponible'), ('DOCUMENT', 'Document disponible'), ('ANNONCE', 'Nouvelle annonce'), ('MESSAGE', 'Nouveau message'), ('DEVOIR', 'Nouveau devoir')], max_length=15, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='CahierTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(default=django.utils.timezone.localdate, verbose_name='date de la séance')),
                ('contenu_seance', models.TextField(help_text='Ce qui a été fait en cours.', verbose_name='contenu de la séance')),
                ('travail_a_faire', models.TextField(blank=True, null=True, verbose_name='travail à faire')),
                ('date_echeance_travail', models.DateField(blank=True, null=True, verbose_name="date d'échéance du travail")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_textes', to='application.classe', verbose_name='classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cahier_textes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_textes', to='application.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'cahier de textes',
                'verbose_name_plural': 'cahiers de textes',
                'ordering': ['-date_seance'],
            },
        ),
    ]
