# Generated by Django 5.2.17 on 2026-08-07 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_notification_type_notification_cahiertexte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahiertexte',
            name='lien',
            field=models.URLField(blank=True, help_text='Lien externe (vidéo, ressource...).', null=True, verbose_name='lien'),
        ),
        migrations.AddField(
            model_name='cahiertexte',
            name='piece_jointe',
            field=models.FileField(blank=True, help_text='PDF, image, ou tout autre document lié à la séance.', null=True, upload_to='cahier_textes/', verbose_name='pièce jointe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.CharField(blank=True, help_text='Ex: A, B, Bilingue... (regroupement au sein du niveau/filière)', max_length=50, null=True, verbose_name='section'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='groupe',
            field=models.CharField(blank=True, help_text='Ex: Groupe A, TP1... pour un cours en sous-groupe plutôt que classe entière.', max_length=50, null=True, verbose_name='groupe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ancien_etablissement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ancien établissement'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="nom du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Ex: +261340000000 ou 0340000000', regex='^\\+?[0-9]{10,15}$')], verbose_name="téléphone du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='dossier_medical',
            field=models.TextField(blank=True, help_text='Allergies, traitements en cours, contre-indications médicales...', null=True, verbose_name='dossier médical'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='situation_familiale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='situation familiale'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='couleur',
            field=models.CharField(default='#6366f1', help_text="Couleur d'affichage dans l'emploi du temps (hexadécimal, ex: #6366f1).", max_length=7, verbose_name='couleur'),
        ),
        migrations.AddField(
            model_name='presencecours',
            name='justification_statut',
            field=models.CharField(choices=[('AUCUNE', 'Aucune justification'), ('EN_ATTENTE', 'En attente de validation'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='AUCUNE', max_length=10, verbose_name='statut de la justification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOTE', 'Nouvelle note'), ('ABSENCE', 'Absence'), ('PAIEMENT', 'Paiement enregistré'), ('BULLETIN', 'Bulletin disponible'), ('DOCUMENT', 'Document disponible'), ('ANNONCE', 'Nouvelle annonce'), ('MESSAGE', 'Nouveau message'), ('DEVOIR', 'Nouveau devoir'), ('DISCIPLINE', 'Événement disciplinaire')], max_length=15, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='DossierEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('VACATAIRE', 'Vacataire'), ('STAGIAIRE', 'Stagiaire')], max_length=15, null=True, verbose_name='type de contrat')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="date d'embauche")),
                ('diplomes', models.TextField(blank=True, null=True, verbose_name='diplômes')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salaire')),
                ('volume_horaire_hebdo', models.DecimalField(blank=True, decimal_places=2, help_text="Heures d'enseignement déclarées par semaine.", max_digits=5, null=True, verbose_name='volume horaire hebdomadaire')),
                ('documents_rh', models.FileField(blank=True, null=True, upload_to='documents_rh/', verbose_name='documents RH')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('enseignant', models.OneToOneField(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_enseignant', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'dossier enseignant',
                'verbose_name_plural': 'dossiers enseignants',
            },
        ),
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='titre')),
                ('type_evenement', models.CharField(choices=[('VACANCES', 'Vacances'), ('EXAMEN', 'Examen'), ('EVENEMENT', 'Événement'), ('REUNION', 'Réunion')], max_length=10, verbose_name="type d'événement")),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_calendrier_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_calendrier', to='application.ecole', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'événement de calendrier',
                'verbose_name_plural': 'événements de calendrier',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EvenementDisciplinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('OBSERVATION', 'Observation'), ('AVERTISSEMENT', 'Avertissement'), ('SANCTION', 'Sanction'), ('EXCLUSION', 'Exclusion'), ('CONVOCATION', 'Convocation'), ('RETENUE', 'Retenue')], max_length=15, verbose_name="type d'événement")),
                ('gravite', models.CharField(choices=[('MINEURE', 'Mineure'), ('MODEREE', 'Modérée'), ('GRAVE', 'Grave')], default='MINEURE', max_length=10, verbose_name='gravité')),
                ('description', models.TextField(verbose_name='description')),
                ('date_evenement', models.DateField(default=django.utils.timezone.localdate, verbose_name="date de l'événement")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_disciplinaires_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_disciplinaires', to='application.etudiant', verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'événement disciplinaire',
                'verbose_name_plural': 'événements disciplinaires',
                'ordering': ['-date_evenement'],
            },
        ),
    ]
