# Generated by Django 5.2.17 on 2026-08-07 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_cahiertexte_lien_cahiertexte_piece_jointe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentJustificatifEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ACTE_NAISSANCE', 'Acte de naissance'), ('CIN_PARENT', "CIN d'un parent/tuteur"), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('PHOTO_IDENTITE', "Photo d'identité"), ('BULLETIN_ANTERIEUR', 'Bulletin établissement antérieur'), ('AUTRE', 'Autre')], max_length=25, verbose_name='type de document')),
                ('fichier', models.FileField(upload_to='documents_etudiants/', verbose_name='fichier')),
                ('libelle', models.CharField(blank=True, max_length=150, null=True, verbose_name='libellé')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_etudiants_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='ajouté par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_justificatifs', to='application.etudiant', verbose_name='étudiant')),
            ],
            options={
                'verbose_name': "document justificatif d'étudiant",
                'verbose_name_plural': "documents justificatifs d'étudiant",
                'ordering': ['-date_ajout'],
            },
        ),
    ]
