# Generated by Django 5.2.17 on 2026-08-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_documentjustificatifetudiant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together=set(),
        ),
    ]
