# Generated by Django 5.2.17 on 2026-08-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_classe_niveau'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matiere',
            name='unique_matiere_code_niveau_sans_filiere',
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matiere',
            name='ecole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='application.ecole', verbose_name='établissement'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(blank=True, help_text='Code court de la matière (ex: MATH, PHYS) — généré automatiquement si laissé vide.', max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='application.niveau', verbose_name='niveau'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('ecole', 'code')},
        ),
    ]
