# Generated by Django 5.2.17 on 2026-08-10 05:58

from django.db import migrations


def populer_ecole_depuis_niveau(apps, schema_editor):
    Matiere = apps.get_model('application', 'Matiere')
    for matiere in Matiere.objects.filter(ecole__isnull=True, niveau__isnull=False):
        matiere.ecole_id = matiere.niveau.ecole_id
        matiere.save(update_fields=['ecole'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_matiere_ecole_step1_nullable'),
    ]

    operations = [
        migrations.RunPython(populer_ecole_depuis_niveau, noop),
    ]
