# Generated by Django 5.2.17 on 2026-08-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_matiere_ecole_step2_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='application.ecole', verbose_name='établissement'),
        ),
    ]
