# Generated by Django 5.2.17 on 2026-08-10 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_matiere_ecole_step3_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='enseignants',
            field=models.ManyToManyField(blank=True, help_text='Enseignants intervenant dans cette classe (au-delà du seul professeur titulaire).', limit_choices_to={'role': 'ENSEIGNANT'}, related_name='classes_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='enseignants'),
        ),
    ]
