# Generated by Django 5.2.17 on 2026-08-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_classe_enseignants'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, help_text="Identifiant de connexion pour les enseignants et étudiants (utilisable à la place de l'email).", max_length=20, null=True, verbose_name='matricule'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Vrai pour un compte créé par un administrateur avec un mot de passe temporaire.', verbose_name='doit changer son mot de passe'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('matricule__isnull', False)), fields=('ecole', 'matricule'), name='unique_matricule_par_ecole'),
        ),
    ]
