# Generated by Django 5.2.17 on 2026-08-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_user_matricule_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscriptionSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_inscription_paye', models.BooleanField(default=False, verbose_name="frais d'inscription payés")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role__in': ['ETUDIANT', 'PARENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_inscription', to=settings.AUTH_USER_MODEL, verbose_name='demande')),
            ],
            options={
                'verbose_name': "suivi de demande d'inscription",
                'verbose_name_plural': "suivis de demandes d'inscription",
            },
        ),
        migrations.CreateModel(
            name='PieceJointeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ACTE_NAISSANCE', 'Acte de naissance'), ('CIN_PARENT', "CIN d'un parent/tuteur"), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('PHOTO_IDENTITE', "Photo d'identité"), ('BULLETIN_ANTERIEUR', 'Bulletin établissement antérieur'), ('AUTRE', 'Autre')], max_length=25, verbose_name='type de document')),
                ('fichier', models.FileField(upload_to='pieces_jointes_inscription/', verbose_name='fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_jointes_inscription_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='ajouté par')),
                ('demandeur', models.ForeignKey(limit_choices_to={'role__in': ['ETUDIANT', 'PARENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes_inscription', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
            ],
            options={
                'verbose_name': "pièce jointe de demande d'inscription",
                'verbose_name_plural': "pièces jointes de demande d'inscription",
                'ordering': ['-date_ajout'],
            },
        ),
    ]
