# Generated by Django 5.2.17 on 2026-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_demande_inscription_suivi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentjustificatifetudiant',
            name='type_document',
            field=models.CharField(choices=[('ACTE_NAISSANCE', 'Acte de naissance'), ('CIN', "Carte d'identité nationale (CIN) de l'étudiant"), ('CIN_PARENT', "CIN d'un parent/tuteur"), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('PHOTO_IDENTITE', "Photo d'identité"), ('BULLETIN_ANTERIEUR', 'Bulletin établissement antérieur'), ('AUTRE', 'Autre')], max_length=25, verbose_name='type de document'),
        ),
        migrations.AlterField(
            model_name='piecejointeinscription',
            name='type_document',
            field=models.CharField(choices=[('ACTE_NAISSANCE', 'Acte de naissance'), ('CIN', "Carte d'identité nationale (CIN) de l'étudiant"), ('CIN_PARENT', "CIN d'un parent/tuteur"), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('PHOTO_IDENTITE', "Photo d'identité"), ('BULLETIN_ANTERIEUR', 'Bulletin établissement antérieur'), ('AUTRE', 'Autre')], max_length=25, verbose_name='type de document'),
        ),
    ]
