# Generated by Django 5.2.17 on 2026-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_document_justificatif_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='frais_ecolage_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant de l'écolage par mois pour cette classe (ex: 100000 Ar/mois).", max_digits=10, null=True, verbose_name='écolage mensuel'),
        ),
        migrations.AddField(
            model_name='classe',
            name='frais_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Frais d'inscription ou de réinscription pour cette classe.", max_digits=10, null=True, verbose_name="droit d'inscription/réinscription"),
        ),
    ]
