# Generated by Django 5.2.17 on 2026-08-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_classe_frais_ecolage'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='frais_reinscription',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Frais de réinscription pour un élève déjà inscrit l'année précédente.", max_digits=10, null=True, verbose_name='droit de réinscription'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='frais_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Frais d'inscription pour un nouvel élève dans cette classe.", max_digits=10, null=True, verbose_name="droit d'inscription"),
        ),
    ]
