# Generated by Django 5.2.17 on 2026-08-11 06:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_classe_frais_reinscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('mois_couvert', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mois couvert')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate, verbose_name='date de paiement')),
                ('mode_paiement', models.CharField(default='Espèces', help_text='Ex: Espèces, Virement, Chèque, Mobile Money...', max_length=50, verbose_name='mode de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='référence')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_salaire', to='application.anneescolaire', verbose_name='année scolaire')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_salaire_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('membre', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_salaire', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'paiement de salaire',
                'verbose_name_plural': 'paiements de salaire',
                'ordering': ['-annee_scolaire__date_debut', 'mois_couvert'],
                'unique_together': {('membre', 'annee_scolaire', 'mois_couvert')},
            },
        ),
    ]
