# Generated by Django 5.2.17 on 2026-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_paiement_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementcalendrier',
            name='source_externe',
            field=models.CharField(blank=True, help_text="UID de l'événement dans la source externe (ex: calendrier des jours fériés), utilisé pour éviter les doublons lors des resynchronisations.", max_length=255, null=True, verbose_name='identifiant externe'),
        ),
        migrations.AlterField(
            model_name='evenementcalendrier',
            name='type_evenement',
            field=models.CharField(choices=[('VACANCES', 'Vacances'), ('EXAMEN', 'Examen'), ('EVENEMENT', 'Événement'), ('REUNION', 'Réunion'), ('JOUR_FERIE', 'Jour férié')], max_length=10, verbose_name="type d'événement"),
        ),
        migrations.AlterUniqueTogether(
            name='evenementcalendrier',
            unique_together={('ecole', 'source_externe')},
        ),
    ]
