# Generated by Django 5.2.17 on 2026-08-12 12:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_evenementcalendrier_source_externe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahiertexte',
            name='heure_echeance_travail',
            field=models.TimeField(blank=True, null=True, verbose_name="heure d'échéance du travail"),
        ),
        migrations.AddField(
            model_name='evenementcalendrier',
            name='cahier_texte',
            field=models.OneToOneField(blank=True, help_text="Entrée de cahier de textes dont cet événement synchronise l'échéance de devoir.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenement_calendrier', to='application.cahiertexte', verbose_name='devoir lié'),
        ),
        migrations.AddField(
            model_name='evenementcalendrier',
            name='classe',
            field=models.ForeignKey(blank=True, help_text="Laisser vide pour un événement concernant tout l'établissement ; renseigner pour un événement visible uniquement par cette classe (ex: échéance de devoir).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements_calendrier', to='application.classe', verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='cahiertexte',
            name='contenu_seance',
            field=models.TextField(blank=True, help_text='Ce qui a été fait en cours (facultatif pour un devoir envoyé hors séance).', verbose_name='contenu de la séance'),
        ),
        migrations.AlterField(
            model_name='evenementcalendrier',
            name='type_evenement',
            field=models.CharField(choices=[('VACANCES', 'Vacances'), ('EXAMEN', 'Examen'), ('EVENEMENT', 'Événement'), ('REUNION', 'Réunion'), ('JOUR_FERIE', 'Jour férié'), ('DEVOIR', 'Devoir')], max_length=10, verbose_name="type d'événement"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOTE', 'Nouvelle note'), ('ABSENCE', 'Absence'), ('PAIEMENT', 'Paiement enregistré'), ('BULLETIN', 'Bulletin disponible'), ('DOCUMENT', 'Document disponible'), ('ANNONCE', 'Nouvelle annonce'), ('MESSAGE', 'Nouveau message'), ('DEVOIR', 'Nouveau devoir'), ('RAPPEL_DEVOIR', 'Rappel de devoir'), ('DISCIPLINE', 'Événement disciplinaire')], max_length=15, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='RappelDevoirEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateField(default=django.utils.timezone.localdate, verbose_name="date d'envoi")),
                ('cahier_texte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_envoyes', to='application.cahiertexte', verbose_name='devoir')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'rappel de devoir envoyé',
                'verbose_name_plural': 'rappels de devoir envoyés',
                'unique_together': {('cahier_texte', 'destinataire', 'date_envoi')},
            },
        ),
    ]
