# Generated by Django 5.2.17 on 2026-08-13 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_cahiertexte_heure_echeance_travail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGroupeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe', to='application.classe', verbose_name='classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe_classes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'message de groupe (classe)',
                'verbose_name_plural': 'messages de groupe (classe)',
                'ordering': ['date_envoi'],
            },
        ),
    ]
