# Generated by Django 5.2.17 on 2026-08-13 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_messagegroupeclasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_ouverte', models.BooleanField(default=True, verbose_name='discussion ouverte')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='application.classe', verbose_name='classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='discussions_classes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'discussion de classe',
                'verbose_name_plural': 'discussions de classe',
                'unique_together': {('classe', 'enseignant')},
            },
        ),
    ]
