# Generated by Django 5.2.17 on 2026-08-13 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_discussionclasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom affiché (par défaut, le nom du fichier).', max_length=150, verbose_name='nom')),
                ('fichier', models.FileField(upload_to='documents_devoirs/', verbose_name='fichier')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="date d'import")),
                ('cahier_texte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_importes', to='application.cahiertexte', verbose_name='devoir')),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_devoirs_importes', to=settings.AUTH_USER_MODEL, verbose_name='importé par')),
            ],
            options={
                'verbose_name': 'document de devoir',
                'verbose_name_plural': 'documents de devoir',
                'ordering': ['-date_import'],
            },
        ),
    ]
