# Generated by Django 5.2.17 on 2026-08-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_documentdevoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroupeclasse',
            name='fichier',
            field=models.FileField(blank=True, help_text='Pièce jointe optionnelle (image, PDF, document...).', null=True, upload_to='messages_groupe_classe/', verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='messagegroupeclasse',
            name='contenu',
            field=models.TextField(blank=True, verbose_name='contenu'),
        ),
    ]
