# Generated by Django 5.2.17 on 2026-08-17 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_messagegroupeclasse_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='jour_echeance_mensuelle',
            field=models.PositiveSmallIntegerField(default=5, help_text="Jour du mois auquel l'écolage mensuel est dû (1 à 28, pour rester valide tous les mois).", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name="jour d'échéance mensuelle"),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='mois_debut_annee_scolaire',
            field=models.PositiveSmallIntegerField(default=9, help_text="Premier mois du cycle des 12 mois d'écolage (1=janvier ... 12=décembre, 9=septembre par défaut). Détermine l'échéancier de l'écolage mensuel.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mois de début du calendrier scolaire'),
        ),
    ]
