# Generated by Django 5.2.17 on 2026-08-21 06:32

from decimal import Decimal
from django.db import migrations, models


def backfill_montant_paye(apps, schema_editor):
    """Les lignes historiques marquées PAYE n'ont pas de `montant_paye` (champ inexistant

    avant cette migration) : on suppose qu'elles ont été payées intégralement, sinon
    l'agrégat `dossier_financier` (qui somme désormais `montant_paye`, pas `montant`) les
    compterait à tort comme non payées.
    """
    PaiementEcolage = apps.get_model('application', 'PaiementEcolage')
    PaiementEcolage.objects.filter(statut='PAYE').update(montant_paye=models.F('montant'))


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_anneescolaire_jour_echeance_mensuelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementecolage',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant effectivement versé à ce jour — peut être inférieur à `montant` (paiement partiel, statut PARTIEL) ; le statut est déduit de ces deux valeurs par le serializer plutôt que saisi indépendamment (voir PaiementEcolageSerializer).', max_digits=10, verbose_name='montant payé'),
        ),
        migrations.AlterField(
            model_name='paiementecolage',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text="Montant dû pour cette échéance (mensualité ou droit d'inscription).", max_digits=10, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='paiementecolage',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=15, verbose_name='statut'),
        ),
        migrations.RunPython(backfill_montant_paye, migrations.RunPython.noop),
    ]
